### ISSUE TITLE
danmaku_energy_map.py运行出错

### ISSUE THREAD

**Issue by AceEcho** [valkjsaaa/danmaku_tools#10]
在auto-bilibili-recorder[3b9ac86]的container里手动运行了以下danmaku_tools指令: 
```
python3 -m danmaku_tools.danmaku_energy_map --graph "/storage/3012597/20230129/3012597-20230129-160250-428.all.he.png" --he_map "/storage/3012597/20230129/3012597-20230129-160250-428.all.he.txt" --sc_list "/storage/3012597/20230129/3012597-20230129-160250-428.all.sc.txt" --he_time "/storage/3012597/20230129/3012597-20230129-160250-428.all.he_pos.txt" --sc_srt "/storage/3012597/20230129/3012597-20230129-160250-428.all.sc.srt" --he_range "/storage/3012597/20230129/3012597-20230129-160250-428.all.he_range.txt" "/storage/3012597/20230129/3012597-20230129-160250-428.all.clean.xml" >> "/storage/3012597/20230129/3012597-20230129-160250-428.all.extras.log" 2>&1
```
报错信息：
> Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.8/dist-packages/danmaku_tools/danmaku_energy_map.py", line 502, in <module>
    slices = gen_danmaku_slices(xml_list, 1)
  File "/usr/local/lib/python3.8/dist-packages/danmaku_tools/danmaku_energy_map.py", line 135, in gen_danmaku_slices
    slices[int(get_time(child))//interval].append(preprocess_danmaku(child.text))
IndexError: list index out of range

上述指令用到的唯一input: 
[3012597-20230129-160250-428.all.xml.zip](https://github.com/valkjsaaa/danmaku_tools/files/10530029/3012597-20230129-160250-428.all.xml.zip)

上面这个xml是由以下两个xml合并来的，for completeness我把文件也放在这里。
[individual_xmls.zip](https://github.com/valkjsaaa/danmaku_tools/files/10530035/individual_xmls.zip)

**Comment by AceEcho** [comment]
找到问题了，合并后的xml最后一条弹幕的时间5569.223比倒数第二条时间戳5575.06小，导致gen_danmaku_slice中的
```
slices[int(get_time(child))//interval]
```
指向了不存在的index报错（这里需要所有child的时间戳是按先后顺序的）。

是两个片段弹幕合并时出现的问题，也就是input问题，跟本repo没关系。

**Comment by AceEcho** [comment]
> 

合并前的两个flv文件长度分别为5565和8左右，但是第一个文件的xml弹幕中出现了5572的时间戳，导致了后续所有的问题。

属于录制的问题，跟本repo没关系，现在我close掉这个issue。
